version: "3"
services:
  app:
    image: docker.io/mgold1234/appwithoutdb
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
volumes:
    db: